package com.travel.dto.admin;

import lombok.AllArgsConstructor;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;

@Getter	@Setter
@AllArgsConstructor
@NoArgsConstructor
public class DTO_SalesChart_admin {
	
	private int order_month;
	private int order_day;
	private int sum_payment_price;
	
	private int s_no;
	private String s_name;
	private String s_type;
}


//SELECT  NVL(SUM(NVL(CASE WHEN EXTRACT(MONTH FROM A.ORDER_DATE)=1 THEN PAYMENT_PRICE END,0)),0) AS JANUARY
//,NVL(SUM(NVL(CASE WHEN EXTRACT(MONTH FROM A.ORDER_DATE)=2 THEN PAYMENT_PRICE END,0)),0) AS FEBRUARY
//,NVL(SUM(NVL(CASE WHEN EXTRACT(MONTH FROM A.ORDER_DATE)=3 THEN PAYMENT_PRICE END,0)),0) AS MARCH
//,NVL(SUM(NVL(CASE WHEN EXTRACT(MONTH FROM A.ORDER_DATE)=4 THEN PAYMENT_PRICE END,0)),0) AS APRIL
//,NVL(SUM(NVL(CASE WHEN EXTRACT(MONTH FROM A.ORDER_DATE)=5 THEN PAYMENT_PRICE END,0)),0) AS MAY
//,NVL(SUM(NVL(CASE WHEN EXTRACT(MONTH FROM A.ORDER_DATE)=6 THEN PAYMENT_PRICE END,0)),0) AS JUNE
//,NVL(SUM(NVL(CASE WHEN EXTRACT(MONTH FROM A.ORDER_DATE)=7 THEN PAYMENT_PRICE END,0)),0) AS JULY
//,NVL(SUM(NVL(CASE WHEN EXTRACT(MONTH FROM A.ORDER_DATE)=8 THEN PAYMENT_PRICE END,0)),0) AS AUGUST
//,NVL(SUM(NVL(CASE WHEN EXTRACT(MONTH FROM A.ORDER_DATE)=9 THEN PAYMENT_PRICE END,0)),0) AS SEPTEMBER
//,NVL(SUM(NVL(CASE WHEN EXTRACT(MONTH FROM A.ORDER_DATE)=10 THEN PAYMENT_PRICE END,0)),0) AS OCTOBER
//,NVL(SUM(NVL(CASE WHEN EXTRACT(MONTH FROM A.ORDER_DATE)=11 THEN PAYMENT_PRICE END,0)),0) AS NOVEMBER
//,NVL(SUM(NVL(CASE WHEN EXTRACT(MONTH FROM A.ORDER_DATE)=12 THEN PAYMENT_PRICE END,0)),0) AS DECEMBER
//FROM
//(
//SELECT  DISTINCT A.ORDER_DATE, A.PAYMENT_PRICE
//FROM    THISORDER A LEFT JOIN THISREFUND B ON A.ORDER_NO = B.ORDER_NO
//                        LEFT JOIN THISORDERDTL C ON A.ORDER_NO = C.ORDER_NO
//WHERE   B.REFUND_NO IS NULL
//AND       C.S_NO = 41
//AND      EXTRACT(YEAR FROM ORDER_DATE) = 2023
//) A